### ISSUE TITLE
Summarization is just concatenating of tweets

### ISSUE THREAD

**Issue by SaketThota** [SSRTDevs/Twitterify#11]
Summary of tweets on Thread Summarizer, Trending Page are getting concatenating, is there anything we can fix that?
If yes, kindly fix it @kafka-654

**Comment by kafka-654** [comment]
Yes, now decreased the maximum limit of summarization model.

**Comment by SaketThota** [comment]
Can we do it as a variable? Depending on the text to summarise.

**Comment by SaketThota** [comment]
Duplicate of issue #10

**Comment by SaketThota** [comment]
Where are we with this?

**Comment by kafka-654** [comment]
Made it variable, Now it will be half of the input tokens
