### ISSUE TITLE
Tweets are getting truncate and some emojis are not supported

### ISSUE THREAD

**Issue by SaketThota** [SSRTDevs/Twitterify#6]
Tweets are getting truncate and some emojis are not supported in profile summary section.

**Comment by SaketThota** [comment]
![image](https://user-images.githubusercontent.com/65193443/218502255-3da69515-f689-4610-8ee4-c874f8622de3.png)

Consider clearing unwanted data in tweet like RT, @SomeUserName and other stuff inside tweet.
Can you have a look at this @kafka-654 ?

**Comment by kafka-654** [comment]
Some emojis are not displaying because they are not supported with our font. Can we try changing it?

**Comment by SaketThota** [comment]
Yes, try changing to any all supported font and similar to Twitter.

**Comment by SaketThota** [comment]
Where are we with this? @Abhi-tech-09 @kafka-654
