### ISSUE TITLE
User profile protected accounts

### ISSUE THREAD

**Issue by SaketThota** [SSRTDevs/Twitterify#8]
![image](https://user-images.githubusercontent.com/65193443/201632377-400e1c1c-4fa8-4fba-9800-73a73b542a61.png)

What shall we do incase of protected accounts?

**Comment by prithvirohira8** [comment]
We can display a message on the frontend for that error, saying that the user profile is protected

**Comment by SaketThota** [comment]
Yes raised just to incase we miss to handle.

**Comment by kafka-654** [comment]
Fixed it.

**Comment by Abhi-tech-09** [comment]
Is this done ?

**Comment by kafka-654** [comment]
Yes

**Comment by SaketThota** [comment]
Did you tested it?

**Comment by kafka-654** [comment]
Yes
