### ISSUE TITLE
Remove unused code and unused library imports

### ISSUE THREAD

**Issue by SaketThota** [SSRTDevs/Twitterify#9]
@kafka-654 you do in [this](https://github.com/SaketThota/BE-project/blob/main/flaskBackend/profileSummarizer/) and [this](https://github.com/SaketThota/BE-project/tree/main/flaskBackend/threadSummarizer) folder files. Also can you refactor code in [this](https://github.com/SaketThota/BE-project/blob/main/flaskBackend/profileSummarizer/processing.py) file. (I think this is your previous project right?)

I will do the same thing in rest of the files.

**Comment by kafka-654** [comment]
Refactored the code in all the three directories.

**Comment by SaketThota** [comment]
Pull the latest code and raise a PR
